-- MySQL Script generated by MySQL Workbench
-- Thu Jun 13 21:20:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema miru
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema miru
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `miru` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `miru` ;

-- -----------------------------------------------------
-- Table `miru`.`estudioanimacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miru`.`estudioanimacion` (
  `id_estudio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_estudio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `miru`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miru`.`genero` (
  `id_genero` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_genero`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `miru`.`contenido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miru`.`contenido` (
  `id_contenido` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `anio_lanzamiento` YEAR NOT NULL,
  `id_genero` INT NOT NULL,
  PRIMARY KEY (`id_contenido`),
  UNIQUE INDEX `id_genero_UNIQUE` (`id_genero` ASC) VISIBLE,
  CONSTRAINT `id_genero`
    FOREIGN KEY (`id_genero`)
    REFERENCES `miru`.`genero` (`id_genero`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `miru`.`anime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miru`.`anime` (
  `id_anime` INT NOT NULL AUTO_INCREMENT,
  `id_contenido` INT NOT NULL,
  `capitulos` INT NULL DEFAULT NULL,
  `id_estudio` INT NOT NULL,
  `id_estado` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_anime`),
  INDEX `id_contenido` (`id_contenido` ASC) VISIBLE,
  INDEX `id_estudio` (`id_estudio` ASC) VISIBLE,
  CONSTRAINT `anime_ibfk_2`
    FOREIGN KEY (`id_estudio`)
    REFERENCES `miru`.`estudioanimacion` (`id_estudio`),
  CONSTRAINT `fk_anime_contenido`
    FOREIGN KEY (`id_contenido`)
    REFERENCES `miru`.`contenido` (`id_contenido`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `miru`.`desarrollador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miru`.`desarrollador` (
  `id_desarrollador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_desarrollador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `miru`.`director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miru`.`director` (
  `id_director` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_director`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `miru`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miru`.`estado` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `nombre_estado` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `miru`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miru`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `año_nacimiento` DATE NOT NULL,
  `edad` INT NOT NULL,
  `genero_de_interes` VARCHAR(45) NULL DEFAULT NULL,
  `suscripcion` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `miru`.`lista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miru`.`lista` (
  `id_lista` INT NOT NULL AUTO_INCREMENT,
  `fecha_creacion` DATE NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_contenido` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_lista`),
  foreign key(id_contenido) references contenido (id_contenido),
  foreign key(id_usuario) references usuario (id_usuario)
  );


-- -----------------------------------------------------
-- Table `miru`.`productora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miru`.`productora` (
  `id_productora` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_productora`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `miru`.`pelicula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miru`.`pelicula` (
  `id_pelicula` INT NOT NULL AUTO_INCREMENT,
  `id_contenido` INT NULL DEFAULT NULL,
  `duracion` INT NULL DEFAULT NULL,
  `id_director` INT NULL DEFAULT NULL,
  `id_productora` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_pelicula`),
  UNIQUE INDEX `id_productora_UNIQUE` (`id_productora` ASC) VISIBLE,
  INDEX `id_contenido` (`id_contenido` ASC) VISIBLE,
  INDEX `id_director` (`id_director` ASC) VISIBLE,
  CONSTRAINT `fk_pelicula_contenido`
    FOREIGN KEY (`id_contenido`)
    REFERENCES `miru`.`contenido` (`id_contenido`)
    ON DELETE CASCADE,
  CONSTRAINT `id_productora`
    FOREIGN KEY (`id_productora`)
    REFERENCES `miru`.`productora` (`id_productora`),
  CONSTRAINT `pelicula_ibfk_2`
    FOREIGN KEY (`id_director`)
    REFERENCES `miru`.`director` (`id_director`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `miru`.`preferencias_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miru`.`preferencias_usuario` (
  `id_preferencia` INT NOT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  `recive_novedades` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_preferencia`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `preferencias_usuario_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `miru`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `miru`.`progreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miru`.`progreso` (
  `id_progreso` INT NOT NULL AUTO_INCREMENT,
  `nombre_progreso` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_progreso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `miru`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miru`.`registro` (
  `id_registro` INT NOT NULL AUTO_INCREMENT,
  `puntuacion` DECIMAL(3,1) NULL DEFAULT NULL,
  `id_estado` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_contenido` INT NOT NULL,
  PRIMARY KEY (`id_registro`),
  INDEX `id_estado_idx` (`id_estado` ASC) VISIBLE,
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `id_contenido_idx` (`id_contenido` ASC) VISIBLE,
  CONSTRAINT `id_cont`
    FOREIGN KEY (`id_contenido`)
    REFERENCES `miru`.`contenido` (`id_contenido`),
  CONSTRAINT `id_estado`
    FOREIGN KEY (`id_estado`)
    REFERENCES `miru`.`estado` (`id_estado`),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `miru`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `miru`.`reseña`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miru`.`reseña` (
  `id_reseña` INT NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `texto` VARCHAR(300) NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_contenido` INT NOT NULL,
  `id_registro` INT NOT NULL,
  PRIMARY KEY (`id_reseña`),
  UNIQUE INDEX `id_contenido_UNIQUE` (`id_contenido` ASC) VISIBLE,
  UNIQUE INDEX `id_registro_UNIQUE` (`id_registro` ASC) VISIBLE,
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `id_con`
    FOREIGN KEY (`id_contenido`)
    REFERENCES `miru`.`contenido` (`id_contenido`),
  CONSTRAINT `id_registro`
    FOREIGN KEY (`id_registro`)
    REFERENCES `miru`.`registro` (`id_registro`),
  CONSTRAINT `id_usu`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `miru`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `miru`.`serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miru`.`serie` (
  `id_serie` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NULL DEFAULT NULL,
  `id_contenido` INT NULL DEFAULT NULL,
  `temporadas` INT NULL DEFAULT NULL,
  `id_director` INT NULL DEFAULT NULL,
  `id_productora` INT NOT NULL,
  `id_estado` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_serie`),
  UNIQUE INDEX `id_productora_UNIQUE` (`id_productora` ASC) VISIBLE,
  INDEX `id_contenido` (`id_contenido` ASC) VISIBLE,
  INDEX `id_director` (`id_director` ASC) VISIBLE,
  CONSTRAINT `fk_serie_contenido`
    FOREIGN KEY (`id_contenido`)
    REFERENCES `miru`.`contenido` (`id_contenido`)
    ON DELETE CASCADE,
  CONSTRAINT `id_produc`
    FOREIGN KEY (`id_productora`)
    REFERENCES `miru`.`productora` (`id_productora`),
  CONSTRAINT `serie_ibfk_2`
    FOREIGN KEY (`id_director`)
    REFERENCES `miru`.`director` (`id_director`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `miru`.`videojuego`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miru`.`videojuego` (
  `id_videojuego` INT NOT NULL AUTO_INCREMENT,
  `id_contenido` INT NULL DEFAULT NULL,
  `plataforma` VARCHAR(255) NULL DEFAULT NULL,
  `id_desarrollador` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_videojuego`),
  INDEX `id_contenido` (`id_contenido` ASC) VISIBLE,
  INDEX `id_desarrollador` (`id_desarrollador` ASC) VISIBLE,
  CONSTRAINT `fk_videojuego_contenido`
    FOREIGN KEY (`id_contenido`)
    REFERENCES `miru`.`contenido` (`id_contenido`)
    ON DELETE CASCADE,
  CONSTRAINT `videojuego_ibfk_2`
    FOREIGN KEY (`id_desarrollador`)
    REFERENCES `miru`.`desarrollador` (`id_desarrollador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- Datos por Defecto
INSERT INTO estado (nombre_estado) VALUES 
("finalizado"),
("en emisión");
INSERT INTO usuario (nombre, correo, contrasena, año_nacimiento, edad, genero_de_interes, suscripcion) VALUES 
("maxi", "maxi@email.com", "maxi", "1991-07-20", 32, "todo", 1),
("eze", "eze@m.com", "eze", "2017-06-23", 7, "infantiles", 1);
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
